data.raw.module["speed-module"].effect = { speed = {bonus = 0.15}, consumption = {bonus = 0.5}};
data.raw.module["speed-module-2"].effect = { speed = {bonus = 0.3}, consumption = {bonus = 0.6}};
data.raw.module["speed-module-3"].effect = { speed = {bonus = 0.45}, consumption = {bonus = 0.7}};
data.raw.module["productivity-module"].effect = { productivity = {bonus = 0.03}, consumption = {bonus = 0.4}, pollution = {bonus = 0.3}, speed = {bonus = -0.15}};
data.raw.module["productivity-module-2"].effect = { productivity = {bonus = 0.06}, consumption = {bonus = 0.6}, pollution = {bonus = 0.4}, speed = {bonus = -0.20}};
data.raw.module["productivity-module-3"].effect = { productivity = {bonus = 0.09}, consumption = {bonus = 0.8}, pollution = {bonus = 0.5}, speed = {bonus = -0.25}};
data.raw.module["effectivity-module"].effect = { consumption = {bonus = -0.15}};
data.raw.module["effectivity-module-2"].effect = { consumption = {bonus = -0.3}};
data.raw.module["effectivity-module-3"].effect = { consumption = {bonus = -0.45}};
data.raw.module["speed-module"].icon = "__5dim_module__/graphics/icon/a1.png";
data.raw.module["speed-module-2"].icon = "__5dim_module__/graphics/icon/a2.png";
data.raw.module["speed-module-3"].icon = "__5dim_module__/graphics/icon/a3.png";
data.raw.module["productivity-module"].icon = "__5dim_module__/graphics/icon/r1.png";
data.raw.module["productivity-module-2"].icon = "__5dim_module__/graphics/icon/r2.png";
data.raw.module["productivity-module-3"].icon = "__5dim_module__/graphics/icon/r3.png";
data.raw.module["effectivity-module"].icon = "__5dim_module__/graphics/icon/v1.png";
data.raw.module["effectivity-module-2"].icon = "__5dim_module__/graphics/icon/v2.png";
data.raw.module["effectivity-module-3"].icon = "__5dim_module__/graphics/icon/v3.png";