require("config")
--Changes
require("prototypes.changes")
--Tech
require("prototypes.tech")
--Nuclear
require("prototypes.centrifugue")
require("prototypes.reactor")
require("prototypes.heat-exchanger")
require("prototypes.turbine")
