require("config")
--Changes
require("prototypes.changes")
--Speed
require("prototypes.speed-4")
require("prototypes.speed-5")
--Productivity
require("prototypes.productivity-4")
require("prototypes.productivity-5")
--Effectivity
require("prototypes.effectivity-4")
require("prototypes.effectivity-5")
--Pollution
require("prototypes.pollution-1")
require("prototypes.pollution-2")
require("prototypes.pollution-3")
require("prototypes.pollution-4")
require("prototypes.pollution-5")
--Mix MK4
require("prototypes.speed-effectivity-4")
require("prototypes.speed-productivity-4")
require("prototypes.speed-pollution-4")
require("prototypes.pollution-effectivity-4")
require("prototypes.pollution-productivity-4")
require("prototypes.effectivity-productivity-4")
--Mix MK5
require("prototypes.speed-effectivity-5")
require("prototypes.speed-productivity-5")
require("prototypes.speed-pollution-5")
require("prototypes.pollution-effectivity-5")
require("prototypes.pollution-productivity-5")
require("prototypes.effectivity-productivity-5")
--Welder
require("prototypes.recipe-category")
require("prototypes.welder")
--Category
require("prototypes.module-category")
--Tech
require("prototypes.tech")
