require("config")
--Changes
require("prototypes.changes")
--Dust
require("prototypes.copper-dust")
require("prototypes.iron-dust")
--Masher
require("prototypes.masher")
require("prototypes.masher-2")
--Furnace
require("prototypes.coal-furnace-3")
require("prototypes.electric-furnace-2")
--Furnace
require("prototypes.industrial-furnace")
require("prototypes.industrial-recipes")
--Recipe
require("prototypes.recipe-category")
--Tech
require("prototypes.tech")
