data.raw.item["bauxite-ore"].subgroup = "plates-ore"
data.raw.item["gold-ore"].subgroup = "plates-ore"
data.raw.item["lead-ore"].subgroup = "plates-ore"
data.raw.item["tin-ore"].subgroup = "plates-ore"
data.raw.item["zinc-ore"].subgroup = "plates-ore"