require("config")
--Changes
require("prototypes.change")
--Entity
require("prototypes.entity")
--Item
require("prototypes.item")
--Recipe
require("prototypes.recipe")
--Technologies
require("prototypes.tech")
--tiles
require("prototypes.tile1")
require("prototypes.tile2")
require("prototypes.tile3")
require("prototypes.tile4")
require("prototypes.tile5")
require("prototypes.tile6")
